### ISSUE TITLE
Zero division error

### ISSUE THREAD

**Issue by rmcclosk** [ArtPoon/kamphir#40]
Appears after running the chain for a while.

```
Traceback (most recent call last):
  File "../kamphir/kamphir.py", line 728, in <module>
    decay=args.toldecay)
  File "../kamphir/kamphir.py", line 490, in abc_mcmc
    ratio = math.exp(-2.*(1.-next_score)/tol) / math.exp(-2.*(1.-cur_score)/tol)
ZeroDivisionError: float division by zero
```

**Comment by rmcclosk** [comment]
Turns out that compute() now returns zero on large pairs of trees (~7000 tips), because of the addition of the coalescence times to the kernel.

The trees I was running this on have times on the order of 20000. The coalescent kernel is calculated on the un-normalized node heights. So these can easily have differences of ~100 each. Suppose (conservatively) that the average difference is 10. Then for 7000 tips,

*kcoal = exp(- 7000 * 100 / 7000) = exp(-100) ≈ 0*.

A possible solution is to normalize the branch lengths before applying this part of the kernel, so that the branch lengths aren't so huge.

**Comment by rmcclosk** [comment]
@ArtPoon Perhaps a more coherent solution would be to penalize the *relative* difference instead of the absolute difference. That is, instead of *exp(- | x - y | / n )*, use *exp( - | x - y | / | x | )*, where *x* is the vector of coalescent times from the target tree, and *y* is the vector from the source tree. Okay to make this change?

**Comment by rmcclosk** [comment]
Actually I think it would be best to use the [cosine of the angle between the vectors](https://en.wikipedia.org/wiki/Dot_product#Geometric_definition), which is a standard similarity measure and is always between 0 and 1.

**Comment by ArtPoon** [comment]
Re: using relative differences, I think this is fine given that the simulated trees are constrained to have the same height as the target tree - so they are equivalent.
