### ISSUE TITLE
Getting negative values for coalescent dot-product kernel

### ISSUE THREAD

**Issue by ArtPoon** [ArtPoon/kamphir#44]

**Comment by rmcclosk** [comment]
That's only possible if some of the node heights are negative. I didn't realize that could happen. Probably the fastest thing to do is just square it.

**Comment by ArtPoon** [comment]
I'm going to shift the origin if there are negative node heights

**Comment by rmcclosk** [comment]
Sorry I didn't consider this. FWIW it doesn't actually make sense to get negative node heights out of colgem if you start the epidemic at time 0. Because then those node heights are before the epidemic started...
